# |========================================================|
# |   ______   ______   .__   __.  _______  __    _______  |
# |  /      | /  __  \  |  \ |  | |   ____||  |  /  _____| |
# | |  ,----'|  |  |  | |   \|  | |  |__   |  | |  |  __   |
# | |  |     |  |  |  | |  . `  | |   __|  |  | |  | |_ |  |
# | |  `----.|  `--'  | |  |\   | |  |     |  | |  |__| |  |
# |  \______| \______/  |__| \__| |__|     |__|  \______|  |
# |                                                        |
# |========================================================|
# | Arquivo gerado para a versão 0.3 do plugin PixCraft    |
# |========================================================|

#===============================
# Configuração da Loja         |
#===============================
shop:
  # Comando que o jogador usa para abrir a loja
  command-name: "loja"

  # Categoria padrão que será aberta ao executar o comando
  default-category: "shop"

  # Arquivo da GUI de confirmação de compra
  confirmation-gui: "confirmation_gui"

#===============================
# Configuração de Pagamento    |
#===============================
payment:
  provider:
    # Nome do provedor de pagamento. No momento, só existe suporte ao Mercadopago.
    name: MERCADOPAGO

    # Token de acesso do provedor de pagamento (ex: Pix ou API externa)
    # IMPORTANTE:
    # Esta integração requer CHECKOUT TRANSPARENTE do Mercado Pago.
    # Configure corretamente seu token de acesso.
    # Tutorial de integração: https://www.youtube.com/watch?v=T39m3F71po8&t=556s
    access-token: "SEU_TOKEN_DE_ACESSO"

  # Se true, o pagamento será cancelado caso o jogador saia do jogo ou o servidor desligue
  cancel-on-leave: false

  # Habilita o webhook para receber notificações de pagamento em tempo real.
  # Se estiver "false", o plugin usará polling automaticamente.
  #
  # COMO CONFIGURAR:
  # 1. Deixe "enabled: true" e escolha uma porta (ex: 8080).
  # 2. Se for testar localmente, use ngrok:
  #       ngrok http 8080
  #    Copie a URL gerada (ex: https://abcd1234.ngrok-free.app).
  # 3. No painel do Mercado Pago, vá em "Notificações Webhook"
  #    e cadastre a URL pública + "/payment":
  #       https://abcd1234.ngrok-free.app/payment
  # 4. Marque apenas os eventos de pagamento.
  # 5. Salve e teste um pagamento — o plugin deve reconhecer instantaneamente.
  #
  webhook:
    enabled: false
    port: 8080

#===============================
# Configuração do QR Code      |
#===============================
qr-code-map:
  # Nome que será exibido no mapa
  displayname: "&b&lCódigo QR"

  # Texto de descrição (lore) do item
  lore:
    - "&7Escaneie este código"
    - "&7para realizar o pagamento."

  # Slot onde o item do QR Code aparecerá na sua hotbar
  # Aceita valores de 0 a 8; se for inválido, retorna 3 por padrão
  slot: 3

#===============================
# Notificações via Discord     |
#===============================
discord:
  notification:
    enable: false
    webhook-url: "URL_DO_SEU_WEBHOOK"
    message:
      content:
      username: "PixCraft"
      avatar_url:
      embeds:
        - title: "Novo pagamento!"
          description: "O jogador **{player_name}** comprou um pacote!"
          color: 3066993
          thumbnail:
            url: "player:{player_name}"
          footer:
            text: "PixCraft"
            icon_url: "https://i.imgur.com/EnPoCGU.png"
          fields:
            - name: "Produto"
              value: "{product}"
              inline: true
            - name: "Valor"
              value: "R${price}"
              inline: false
            - name: "Data do pagamento"
              value: "{date}"
              inline: false