mercadopago:
  access-token: "TOKEN"

  #⚙️ Configuração do webhook para notificações de pagamento.
  webhook:
    enabled: false  # Se "false", o plugin usará a verificação periódica.
    port: 8080      # Porta onde o servidor HTTP interno será iniciado.

discord:
  notifications:
    enabled: false
    webhook-url: "webhook_url"
    embed:
      player-head-icon: true  # Exibir o avatar do jogador no embed.
      color: "#1aff00"        # Cor da borda do embed no Discord.
      title: "Nova venda efetuada!"
      description: "Comprador: {player}"
      field:
        enabled: true
        title: "Produto: {product} | Valor pago: R${price}"
        description: "Data da compra: {date}"
