name: PixCraft
version: '${project.version}'
main: br.com.din.pixcraft.PixCraft
api-version: '1.14'
authors: [Dinz1n]
description: Sistema de pagamentos via PIX no Minecraft
softdepend: [NBTAPI]
commands:
  pixcraft:
    description: Comando principal do plugin.
    usage: /<command> <reload|product|menu>
    aliases: [pc]
    permissions:
        pixcraft.command:
          description: Permite o uso do comando principal do plugin.
          default: op