# Produtos da loja
espada-de-diamante:
  name: "Espada de Diamante"
  price: 0.10
  reward:
    - "give {player} diamond_sword 1"

espada-de-ferro:
  name: "Espada de Ferro Cabulosa"
  price: 2.00
  reward:
    - "give {player} iron_sword 1"

armadura-de-diamante:
  name: "Conjunto de Armadura de Diamante"
  price: 15.00
  reward:
    - "give {player} diamond_helmet 1"
    - "give {player} diamond_chestplate 1"
    - "give {player} diamond_leggings 1"
    - "give {player} diamond_boots 1"

kit-iniciante:
  name: "Kit Iniciante"
  price: 5.00
  reward:
    - "give {player} wooden_sword 1"
    - "give {player} stone_pickaxe 1"
    - "give {player} bread 16"
    - "give {player} torch 32"

vip1:
  name: "VIP Bem Legal"
  price: 20.00
  reward:
    - "lp user {player} parent add vip"

vip2:
  name: "VIP Plus"
  price: 14.99
  reward:
    - "lp user {player} parent add outrovip"

bundle-avancado:
  name: "Bundle Avançado"
  price: 30.00
  reward:
    - "give {player} diamond_sword 1"
    - "give {player} diamond_chestplate 1"
    - "give {player} golden_apple 5"
    - "lp user {player} parent add vip"