# |===========================================================================================|
# | .______   .______       ______    _______   __    __    ______ .___________.     _______. |
# | |   _  \  |   _  \     /  __  \  |       \ |  |  |  |  /      ||           |    /       | |
# | |  |_)  | |  |_)  |   |  |  |  | |  .--.  ||  |  |  | |  ,----'`---|  |----`   |   (----` |
# | |   ___/  |      /    |  |  |  | |  |  |  ||  |  |  | |  |         |  |         \   \     |
# | |  |      |  |\  \--. |  `--'  | |  '--'  ||  `--'  | |  `----.    |  |    .----)   |     |
# | | _|      | _| `.___|  \______/  |_______/  \______/   \______|    |__|    |_______/      |
# |                                                                                           |
# |===========================================================================================|
# | Arquivo gerado para a versão 0.1 do plugin PixCraft.                                      |
# |===========================================================================================|
#
# ==============================
# EXEMPLO DE PRODUCTS.YML      |
# ==============================
# Cada produto possui:
#   id-do-produto: identificador único (usado no target dos botões)
#   name: Nome do produto que aparecerá no banco e nas notificações
#   price: Preço do produto em reais (ou moeda que você definiu)
#   reward: Lista de comandos que serão executados quando a compra for aprovada
#           Use {player} para referenciar o nome do jogador.

# ==============================
# Vips                         |
# ==============================

vip-mensal:
  name: "Vip Mensal"
  price: 10.0
  reward:
    - "lp user {player} parent add vip"

vip-semestral:
  name: "Vip Semestral"
  price: 50.0
  reward:
    - "lp user {player} parent add vip"

vip-anual:
  name: "Vip Anual"
  price: 90.0
  reward:
    - "lp user {player} parent add vip"

# ==============================
# Kits                         |
# ==============================

kit-iniciante:
  name: "Kit Iniciante"
  price: 5.0
  reward:
    - "give {player} minecraft:wooden_pickaxe 1"
    - "give {player} minecraft:apple 5"

kit-avancado:
  name: "Kit Avançado"
  price: 15.0
  reward:
    - "give {player} minecraft:stone_pickaxe 1"
    - "give {player} minecraft:cooked_beef 10"
    - "msg {player} &aVocê recebeu o Kit Avançado!"

kit-profissional:
  name: "Kit Profissional"
  price: 25.0
  reward:
    - "give {player} minecraft:iron_pickaxe 1"
    - "give {player} minecraft:cooked_beef 15"

kit-elite:
  name: "Kit Elite"
  price: 40.0
  reward:
    - "give {player} minecraft:diamond_pickaxe 1"
    - "give {player} minecraft:diamond 3"

kit-lendario:
  name: "Kit Lendário"
  price: 60.0
  reward:
    - "give {player} minecraft:netherite_pickaxe 1"
    - "give {player} minecraft:netherite_ingot 2"

# ==============================
# Espadas                      |
# ==============================

espada-de-madeira:
  name: "Espada de Madeira"
  price: 1.0
  reward:
    - "give {player} minecraft:wooden_sword 1"

espada-de-pedra:
  name: "Espada de Pedra"
  price: 2.0
  reward:
    - "give {player} minecraft:stone_sword 1"

espada-de-ouro:
  name: "Espada de Ouro"
  price: 2.0
  reward:
    - "give {player} minecraft:golden_sword 1"

espada-de-ferro:
  name: "Espada de Ferro"
